### ISSUE TITLE
Suggestion: Add labels for fields on the UI

### ISSUE THREAD

**Issue by LeigerGaming** [Redstoner-2019/MinecraftMapEditor#3]
It's unclear what most of these fields do :)

![image](https://user-images.githubusercontent.com/71436104/227728743-df380360-4227-4df0-b9ee-a2bb6b641a87.png)

**Comment by Redstoner-2019** [comment]
Hi, do you have any tips on how I can make it more understandable what the coordinate input fields do? I thought of maybe adding a hover text.

**Comment by Redstoner-2019** [comment]
Improved with latest release.
